baseurl = "https://maintainerati.org/"
languageCode = "en-us"
title = "Maintainerati"
publishDir = "docs"

[params]
  description = "An unconference, open space for open source software maintainers."
  author = "The Maintainerati"
  date = "19 November, 2017"
  [params.location]
    name = "Xebia"
    city = "Amsterdam"
    url = "https://xebia.com/"
