baseurl = "https://maintainerati.org/"
languageCode = "en-us"
title = "Maintainerati"
publishDir = "docs"


theme = "gohugo-theme-ananke"
# MetaDataFormat = "yaml"
defaultContentLanguage = "en"
paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-136503208-1"

enableRobotsTXT = true

# [sitemap]
#   changefreq = "monthly"
#   priority = 0.5
#   filename = "sitemap.xml"

[menu]

  [[menu.main]]
  identifier = "blog"
  name = "Blog"
  title = "blog section"
  url = "/blog/"
  weight = 100

  [[menu.main]]
  identifier = "code-of-conduct"
  name = "Code of Conduct"
  title = "code of conduct"
  url = "/code-of-conduct/"
  weight = 20

  [[menu.main]]
  identifier = "diversity-statement"
  name = "Diversity Statement"
  title = "diversity statement"
  url = "/diversity-statement/"
  weight = 10

  [[menu.main]]
  identifier = "berlin-2019"
  name = "Berlin 2019"
  title = "berlin 2019"
  url = "/berlin-2019/"
  weight = 1

[params]
  favicon = "favicon.ico"
  description = "An unconference for open source software maintainers."
  facebook = ""
  twitter = "https://twitter.com/Maintainerati"
  instagram = ""
  youtube = ""
  github = "https://github.com/Maintainerati"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-white"
  featured_image = "/img/hero.jpeg"
  recent_posts_number = 2
