baseurl = "https://maintainerati.org/"
languageCode = "en-us"
title = "Maintainerati"

[params]
  description = "An unconference, open space for open source software maintainers."
  author = "The Maintainerati"
  date = "10 October, 2017"
  [params.location]
    name = "The Laundry SF"
    city = "San Francisco"
    url = "http://thelaundrysf.com/"
