baseurl = "http://localhost:8273/"
languageCode = "en-us"
title = "Maintainerati"
publishDir = "docs"

# [params]
  # description = "An unconference, open space for open source software maintainers."
  # author = "The Maintainerati"
  # date = "19 November, 2017"
  # [params.location]
    # name = "Xebia"
    # city = "Amsterdam"
    # url = "https://xebia.com/"


theme = "gohugo-theme-ananke"
# MetaDataFormat = "yaml"
defaultContentLanguage = "en"
paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
# googleAnalytics = ""
enableRobotsTXT = true

# [sitemap]
#   changefreq = "monthly"
#   priority = 0.5
#   filename = "sitemap.xml"

[menu]

  [[menu.main]]
  identifier = "blog"
  name = "Blog"
  title = "blog section"
  url = "/blog/"
  weight = 0

  [[menu.main]]
  identifier = "code-of-conduct"
  name = "Code of Conduct"
  title = "code of conduct"
  url = "/code-of-conduct/"
  weight = 20

  [[menu.main]]
  identifier = "diversity-statement"
  name = "Diversity Statement"
  title = "diversity statement"
  url = "/diversity-statement/"
  weight = 10


[params]
  favicon = ""
  description = "An unconference for open source software maintainers."
  facebook = ""
  twitter = "https://twitter.com/Maintainerati"
  instagram = ""
  youtube = ""
  github = "https://github.com/Maintainerati"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/img/hero.jpeg"
  recent_posts_number = 2
